### PR TITLE
made the setup.py classifiers more specific 

### PR DESCRIPTION
**Pull request by lsh-0**
These classifiers are regarding which versions of python are supported, making support for Python 3 explicit.

It's these classifiers that helps [this tool](https://github.com/brettcannon/caniusepython3) (`caniusepython3`) understand this project won't be a blocker to Python 3 migration.

That tool was discovered via [this article](https://tech.yplanapp.com/2016/08/24/upgrading-to-python-3-with-zero-downtime/).

### CODE REVIEW

**Comment by lsh-0** [comment]
Hi @svetlyak40wt , can I get this accepted or refused, please?

**Comment by svetlyak40wt** [comment]
Sure. Excuse me for delay. Mostly interested in Common Lisp these days :)

**Comment by lsh-0** [comment]
cheers

**Comment by svetlyak40wt** [comment]
I've released 0.3.1 version with fixed classifiers.

**Comment by lsh-0** [comment]
excellent, thanks again.

**Pull request merged**
